export const ROUTES = {
  HOME: 'HOME',
  SIGNIN: 'SIGNIN',
  ACTIVITY: 'ACTIVITY',
  GREENCREDEIT: 'GREENCREDEIT',
  CREATEPOST: 'CREATEPOST',
  INTRO: 'INTRO',
  SPLASH: 'SPLASH',
  REDEEM: 'REDEEM',
  CAMERA:'CAMERA',
  COMMENT:'COMMENT',
};
