export const actionTypes = {
  //user
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCESS: "SIGNUP_SUCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCESS: "LOGIN_SUCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
}

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCESS: "LOGIN_SUCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCESS: "LOGOUT_SUCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const postTypes = {
  POST_REQUEST: "POST_REQUEST",
  POST_FAILURE: "POST_FAILURE",
  POST_SUCESS: "POST_SUCESS",
  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE"
}

export const greenCreditTypes = {
  GREEN_CREDIT_REQUEST: "GREEN_CREDIT_REQUEST",
  GREEN_CREDIT_FAILURE: "GREEN_CREDIT_FAILURE",
  GREEN_CREDIT_SUCESS: "GREEN_CREDIT_SUCESS"
}