export const ActionTypes = {
    //user
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCESS: "SIGNUP_SUCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCESS: "LOGIN_SUCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
}

export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCESS: "LOGIN_SUCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCESS: "LOGOUT_SUCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  };

  export const PostTypes={
    POST_REQUEST:"POST REQUEST",
    POST_FAILURE:"POST_FAILURE",
    POST_SUCESS:"POST_SUCESS",
  }