# Generated by Django 4.0 on 2022-01-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0002_alter_greencredituser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greencredituser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
