# Generated by Django 4.0 on 2022-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0003_alter_greencredituser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='greencredituser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
