# Generated by Django 4.0 on 2022-01-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0004_greencredituser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='greencredituser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='greencredituser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
