# Generated by Django 4.0 on 2022-01-17 18:38

from django.db import migrations, models
import django.db.models.deletion
import greencredit_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0005_greencredituser_auth_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_urls', models.ImageField(blank=True, null=True, upload_to=greencredit_api.models.activity_photo_urls)),
                ('geo_location', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.JSONField(blank=True, default='[]', null=True)),
                ('md5hash', models.TextField(blank=True, null=True)),
                ('post_tesxt', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greencredit_api.greencredituser')),
            ],
        ),
    ]
