# Generated by Django 4.0 on 2022-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0008_alter_activity_photo_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='photo_urls',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
    ]
