# Generated by Django 4.0 on 2022-01-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0009_alter_activity_photo_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greencredituser',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='greencredituser',
            old_name='modified_on',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='greencredituser',
            name='role',
            field=models.CharField(choices=[('ACTIVIST', 'ACTIVIST'), ('ENTITY', 'ENTITY'), ('FUNDER', 'FUNDER')], default='ACTIVIST', max_length=20),
        ),
        migrations.AddField(
            model_name='greencredituser',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
