# Generated by Django 4.0 on 2022-01-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0010_rename_created_on_greencredituser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greencredituser',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
