# Generated by Django 4.0 on 2022-08-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0014_creditpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='updatedAtTimestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='greencredituser',
            name='followers',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='greencredituser',
            name='following',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
    ]
