# Generated by Django 4.0 on 2022-08-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0015_activity_comments_activity_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
