# Generated by Django 4.0 on 2022-08-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit_api', '0016_activity_comments_activity_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='meta',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='greencredituser',
            name='meta',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='greencredituser',
            name='followers',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='greencredituser',
            name='following',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
